<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="14.0.0" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
      <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="8.0.14" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="Serilog" Version="4.2.0" />
      <PackageReference Include="System.Threading.RateLimiting" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore">
        <HintPath>..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.12\Microsoft.AspNetCore.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.AspNetCore.WebUtilities">
        <HintPath>..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.15\Microsoft.AspNetCore.WebUtilities.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ProjectDroit.Core\ProjectDroit.Core.csproj" />
      <ProjectReference Include="..\ProjectDroit.Domain\ProjectDroit.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Http\Exceptions\" />
      <Folder Include="Http\Gemini\Mappings\" />
    </ItemGroup>

</Project>
